version: "3.1"
services:
  kart:
    image: kart
    container_name: kart
    privileged: true
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./kart:/kart
    build:
      context: ./kart
      dockerfile: Dockerfile